### ISSUE TITLE
Save package without Modelica library

### ISSUE THREAD

**Issue by christiankral** [Philipp-pf/district-heating#2]
The actual version a0b05eb contains parts of the Modelica standard library. This effect may have been caused by saving the package by "Save Total" in Dymola. In order to remove Modelica the following steps shall be performed:
- Open Dymola
- Open Modelica Standard Library (double click)
- Load your package DistrictHeating
- Use "Save As" to re-store your package

**Comment by Philipp-pf** [comment]
Fixed with new version 5d5420ce25b2ae32b7c8846628eb3d930f1436b0
