### ISSUE TITLE
Use relative file paths to load resources

### ISSUE THREAD

**Issue by christiankral** [Philipp-pf/district-heating#3]
The following examples shall not use an absolute path to access a data file:

- ``DistrictHeating.Calibration.CalibrationOriginalFirstTryShort``
- ``DistrictHeating.Calibration.CalibrationOriginalFirstTryLong``
- ``DistrictHeating.Calibration.StoreHeatFlowLosses``
- ``DistrictHeating.Calibration.average_data``

Instead the relative file path shall be indicated by

```modelica
Modelica.Utilities.Files.loadResource(
  "modelica://DistrictHeating/Resources/Data/xxx.txt")
```

**Comment by Philipp-pf** [comment]
fixed with new version 01dd4cac905ef0b3d654972a12fcf7c183d5b702
