### ISSUE TITLE
Start class names with uppercase letter

### ISSUE THREAD

**Issue by christiankral** [Philipp-pf/district-heating#4]
All Modelica classes except functions shall start with an uppercase letter. Particularly this refers to:

- ``Modelica.Utilities.Files.loadResource``

**Comment by christiankral** [comment]
This also refers to package names; they are always supposed to start with uppercase letters.

**Comment by Philipp-pf** [comment]
Fixed with new version 5d5420ce25b2ae32b7c8846628eb3d930f1436b0
