### ISSUE TITLE
Include license in Modelica library

### ISSUE THREAD

**Issue by christiankral** [Philipp-pf/district-heating#9]
The license text of LICENSE in https://github.com/Philipp-pf/district-heating/commit/012fe83b7459c94857ab802705a42d671c090bb8 shall also be included in the Modelica library. If the library is distributed the connection to the Github repository may be lost as it is not stated in the Modelica library.

It may also make sense to include the author information and possibly a link to the PDF file of the master thesis (if the FH Technikum Wien gives permission to publish this work on Github).

The included files 

- https://github.com/Philipp-pf/district-heating/blob/master/DistrictHeating/Resources/Images/320px-Tutg.svg.png
- https://github.com/Philipp-pf/district-heating/blob/master/DistrictHeating/Resources/Images/fire-30276_960_720.png

do not have a copyright and license information. Even if the use may be free, a copyright notice might be required or advisable. An example of showing a third party license is shown in https://github.com/christiankral/PhotoVoltaics/blob/master/PhotoVoltaics/UsersGuide/License.mo

**Comment by Philipp-pf** [comment]
The new commit 47598ccdc93b06f5c1d831a36a32e621eae8f020 contains a package "users guide" which includes license information.
